#!/bin/sh

#autostart
pgrep -x sxhkd > /dev/null || sxhkd &
xsetroot -cursor_name left_ptr
pkill picom
picom &

#Only use with higher screen res.
xrandr --output DP-4 --primary --mode 5120x1440 --rate 120.00 

if xrandr -q | grep "DP-2 connected"; then
  xrandr --output DP-2 --mode 2560x1440 --above DP-4
fi

bash ~/.config/polybar/scripts/pywal.sh ~/1-vault/2-media/1-wallpapers/wpa.png
~/.config/polybar/launch.sh 

#monitor
bspc monitor DP-4 -d 1 2 3 4
bspc monitor DP-2 -d 5 6 7 8

#window information
bspc config border_width 0 
bspc config window_gap 9
bspc config pointer_follows_monitor true
bspc config focus_follows_pointer true

