#
# MakeMKV settings file, written by MakeMKV v1.18.4 linux(x64-release)
#

kslc_c89c7837ae7e1b74 = "00000405"
path_DestDirMRU = "*/home/si/tmp"
path_OpenFile = "/home/si/rips/Tsumugi Secrets In The Attic/VIDEO_TS/"
screen_geometry = "AdnQywADAAAAAAAAAAAAAAAABOwAAAKtAAAAAAAAAAAAAAT6AAACtgAAAAACAAAAFAAAAAAAAAAAAAAABOwAAAKt"
screen_state = "AAAA/wAAAAD9AAAAAAAABO0AAAJVAAAABAAAAAQAAAAIAAAACPwAAAABAAAAAgAAAAEAAAAWAE0AYQBpAG4AVABvAG8AbABiAGEAcgEAAAAA/////wAAAAAAAAAA"

