#
# MakeMKV settings file, written by MakeMKV v1.18.4 linux(x64-release)
#

app_DestinationDir = "/home/si/tmp"
app_ExpertMode = "1"
app_Java = ""
app_Key = "M-DjuvYxn4rDUQOb6qT9C8Z0PSpKArHQCbOMRIOcyXLc@NuCv2_BqYyEi2n@Xfj1WifR"
app_Proxy = ""
app_ccextractor = ""
sdf_Stop = ""
speed_HL-DT-ST_BDDVDRW_CH10LS20_1.01_20110707123456_K9CB3F25430 = ""

